### ISSUE TITLE
config.txtがないと言われる

### ISSUE THREAD

**Issue by takeokato719** [wistaria/MateriAppsInstaller#100]
gcc10のインストールを行うために

sh ./install.sh

を実行したところ、config.txtがないと怒られました。該当箇所をみると

. config.txt

とありますが、これを

./config.txt

と直したら通りました。これはバグだと思うのですが、いかがでしょうか？

**Comment by wistaria** [comment]
一通り直しました 6f9538d42884330f0a0cd8ae12219a920d928ca6
