### ISSUE TITLE
Quantum Espresso - Mac GCC Error

### ISSUE THREAD

**Issue by Ardalanhayatifar** [wistaria/MateriAppsInstaller#122]
I'm following the instructions [here](https://ma.issp.u-tokyo.ac.jp/en/app-post/5274) but I can't get past **Step 6** `sh $HOME/MateriAppsInstaller/tools/gcc-wrapper/install.sh`, resulting in the error: `Error: Homebrew GCC compiler not found`.

I have tried:

• `export PATH=/usr/local/Cellar/gcc/11.3.0_1/bin:$PATH`

**Comment by wistaria** [comment]
Please update MateriAppsInstaller:
```
cd $HOME/MateriAppsInstaller
git pull
```
and try step 6 again.

**Comment by Ardalanhayatifar** [comment]
Thanks! 
I also had to remove `gcc` from `3 sh $HOME/MateriAppsInstaller/apps/espresso/install.sh gcc` in order for it to work.

**Comment by wistaria** [comment]
I have fixed the web page. Thank you very much for your report.
