### ISSUE TITLE
Oakbridge-CX(東大情報基盤センター)でのQEのインストール

### ISSUE THREAD

**Issue by tmisawa** [wistaria/MateriAppsInstaller#123]
MA Installer開発者の皆様へ

MA installer (v.1.1.0)でQEをobcxにインストール (`sh install.sh intel`)しようとしたのですが、
以下のようなエラーがでてコンパイルに失敗してしまいます。

```
xmltools.f90:823.18:

       cp = c_loc(zmat)
                  1
エラー: Assumed-shape array 'zmat' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
```

obcxでの環境は以下となっています。
```
$ module list
Currently Loaded Modulefiles:
  1) impi/2019.9.304    2) intel/2020.4.304   3) python/3.7.3
```

素人質問ですみませんが、対応方法についてご教示いただけると助かります。
よろしくお願いします。

**Comment by wistaria** [comment]
古いGCC使ってます？？
https://lists.quantum-espresso.org/pipermail/users/2020-November/046420.html

**Comment by tmisawa** [comment]
ご返信ありがとうございます。

確かに, gfortranのバージョンが古かったです。

```
$ mpif90 --version
GNU Fortran (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
```

ただ、moduleで追加できる、
`intel/20**`に中に含まれるmpif90はすべてgcc 4.8.5で
`gcc/7.5.0` とconflictしてしまい、gcc>4.9とifortを共存させられないですね。

**Comment by k-yoshimi** [comment]
@tmisawa 
さすがにgccが古すぎるのでobcxに上げてもらうよう、問い合わせた方がいいのではないでしょうか？

**Comment by tmisawa** [comment]
@k-yoshimi 
問い合わせました。

**Comment by tmisawa** [comment]
`module load devtoolset/7`でgcc 7.3を使用できるようになりました。
ただ、それでも、以下のようなエラーで落ちてしまいます。
```
read_upf_schema.f90
f951: Fatal Error: Reading module ‘fox_dom’ at line 1 column 2: Unexpected EOF
```

結局、configureでmake.incを生成して、以下のように
することでコンパイルできました。
```
MPIF90      = mpiifort
F90            = ifort
CC             = icc
F77            = ifort
```
 configureでF90=ifortと指定しても、`F90=gfortran`となぜかなってしまうので、
結局は手動でmake.incを編集することが必要でした。

**Comment by tmisawa** [comment]
追記です。

intelコンパイラを指定してmake.inkを生成してもblasがなぜか、gccのものをリンクするので、
`BLAS_LIBS = -lmkl_gf_lp64 -lmkl_gnu_thread -lmkl_core`
を
`BLAS_LIBS = -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core`
に変更する必要がありました。

これをしないと zdotcまわりのエラーでpw2wannier90.xが落ちました。
