### ISSUE TITLE
Manualの修正

### ISSUE THREAD

**Issue by wistaria** [wistaria/MateriAppsInstaller#126]
https://wistaria.github.io/MateriAppsInstaller/manual/master/en/how_to_use/index.html#install のインデントがおかしい

**Comment by k-yoshimi** [comment]
@wistaria 
> Move to each software directory and run `` install.sh``.

こちらでしょうか？

**Comment by wistaria** [comment]
はい。続きの部分が全部コードブロックに入ってしまっています

**Comment by k-yoshimi** [comment]
@wistaria 
masterブランチの方に修正を反映しました。
@yomichi 
gh-pagesに更新は自動反映するよう設定はされているでしょうか？

**Comment by k-yoshimi** [comment]
チュートリアルにあるMacのOSがCatalinaで古いので、アップデートする。

**Comment by yomichi** [comment]
#133 で自動反映を導入しました
