### ISSUE TITLE
「お問い合せ」ページのリンク切れ

### ISSUE THREAD

**Issue by wistaria** [wistaria/MateriAppsInstaller#129]
* https://www.pasums.issp.u-tokyo.ac.jp/mainstaller/contact/ 
* https://www.pasums.issp.u-tokyo.ac.jp/mainstaller/en/contact/

の Issues へのリンクが切れている。リンク先を https://github.com/wistaria/MateriAppsInstaller/issues に修正

**Comment by k-yoshimi** [comment]
@wistaria 
ご指摘ありがとうございます。修正しました。
