### ISSUE TITLE
ALPS がCMake で落ちる

### ISSUE THREAD

**Issue by yomichi** [wistaria/MateriAppsInstaller#14]
Boost が全ソースコードじゃなくて、header + pre-build library のみに変わったけれど、
ALPS 用のCMake に`-DBoost_ROOT_DIR=$BOOST_ROOT` を渡しているため。
この行を消せば動くはずです。

**Comment by wistaria** [comment]
その前に Fujitsu C++ で bjam を動かさなくては、、、

**Comment by yomichi** [comment]
c8ccfdbdf00d97ba68a9401cad2bdfbd65008ee9
にて解決済み
