### ISSUE TITLE
MateriApps Installerの目標の趣旨

### ISSUE THREAD

**Issue by kensuke1084** [wistaria/MateriAppsInstaller#15]
下記のどちらを想定して対応すればよろしいでしょうか。
(1) 単に「アプリを主要なスパコン全てにインストール」するのが目標
(2) (Installerを使うことで)MateriApps LIVE!と同一version & configurationで揃えるのが目標

(1)の場合だと通常のアプリケーションのインストールと同じでInstallerを参考にしてインストールしますが、(2)の場合、同じアプリケーションがインストールされていても改めてMateriApps用に用意（運用のイメージとしてはMateriAppsの下に各アプリケーションを配置）するのが良いかと考えています。

**Comment by wistaria** [comment]
全部(2)である必要はないと思います。まずは(1)でも良いと思いますが、(1)だと
- インストールの際の小さな不具合への対処などのノウハウが蓄積・共有されない
- バージョンが古くなりがち

などの問題がるので、最終的には(2)にまとめた方が、人的コストの上でも、サービスの質という意味でも望ましいと思います。
