### ISSUE TITLE
ma_revision対応

### ISSUE THREAD

**Issue by wistaria** [wistaria/MateriAppsInstaller#18]
envとermodのみ対応済み
他も順次対応

**Comment by wistaria** [comment]
Lapack, gromacs 対応済み

**Comment by wistaria** [comment]
fftw 対応済み

**Comment by wistaria** [comment]
対応済: env lapack fftw tcltk gsl hdf5 wxWidgets python boost cmake git alps feram gromacs lammps ermod dsqss
未対応: qt4 Komega wxPython alpscore gcc49 xtapp openmx modylas HPhi mVMC tapioca xcrysden iginition

**Comment by yomichi** [comment]
ma_revision は 1-origin ですか？
