### ISSUE TITLE
hdf5のFortran interfaceとalpsの関係

### ISSUE THREAD

**Issue by kensuke1084** [wistaria/MateriAppsInstaller#24]
alpsではhdf5のFortran interfaceを使っているようですが、一方でMateriAppsInstallerのhdf5のconfigure時に--enable-fortranが指定されていないため、Fortran interfaceがインストールされません。
どのように扱うのがよいでしょうか。

**Comment by wistaria** [comment]
ALPS全体のコンパイルには問題ないと思います。おそらく applications/dmrg/tebd が build されていないですね。--enable-fortran を付けてコンパイルするように修正しておきます。
