### ISSUE TITLE
alpsのctestでのエラー

### ISSUE THREAD

**Issue by kensuke1084** [wistaria/MateriAppsInstaller#25]
alpsでhdf5のFortran interfaceを含めてコンパイルして、ctestを行うと、152個のテストのうち、1つがFAILEDとなります。
The following tests FAILED:
        115 - expression (Failed)
cmakeに慣れていないため、エラーの詳細を確認する方法を教えて頂ければ幸いです。

**Comment by wistaria** [comment]
レポートありがとうございます。このfailは特に実害はないので無視して大丈夫です。よろしくお願いします。
