### ISSUE TITLE
link.sh はどこで実行されるのでしょうか？

### ISSUE THREAD

**Issue by halm** [wistaria/MateriAppsInstaller#26]
「京」ログインノードでインストール作業をしているのですが，これが動いてないせいで env.d 以下が空になってます．

**Comment by wistaria** [comment]
link.sh は手で実行します。手順としては、以下の通りです。
- fx10.sh 等でインストール
- cmake/cmakevars-3.2.1-1.sh 等を直接読み込んでテスト
- 動作が確認できたら link.sh を実行して、env.d へのリンクを作成

**Comment by halm** [comment]
わかりました．ありがとうございます．

**Comment by halm** [comment]
「京」にツールはインストール終了
