### ISSUE TITLE
DSQSSインストーラの追加

### ISSUE THREAD

**Issue by wistaria** [wistaria/MateriAppsInstaller#31]

**Comment by yomichi** [comment]
近いうちに新しいバージョンを公開する予定になっているので、少々お待ちください。

**Comment by wistaria** [comment]
新しいバージョンを公開したらお知らせください。DSQSSの講習会が(今のところ)11月下旬に予定されているということなので、それまでにMateriApps LIVE!、Installerの両方とも対応したいです。
