### ISSUE TITLE
xTAPP-util のインストールに失敗する

### ISSUE THREAD

**Issue by yomichi** [wistaria/MateriAppsInstaller#43]
`intel-mkl.sh` at sekirei。たぶん他のマシンや `macos.sh` も同じだと思います。

エラーメッセージ。

``` bash
[make install xtapp-util]
Makefile:1: *** mixed implicit and normal rules: deprecated syntax
make: *** ターゲット 'install' を make するルールがありません.  中止.
```

util のMakefile には `install` ターゲットが無いようです。

``` bash
$ cat build/xtapp_150401/xtapp-util_150401/Makefile
tools %:
        make $@ -C fldtool
        make $@ -C inputconv
        make $@ -C mdtool
        make $@ -C minmaxband
        make $@ -C wfchg2pdos
```

あと、 `util/fldtool/Makefile` ですが、 `setup.sh` で `debian/patch/makefile-1.patch` を当てる影響で、 `xtapp-intel-mkl.patch` による `install` ターゲットの置き換え（ `DESTDIR` -> `PREFIX` ）に失敗しているようです。他にもあるかもしれません。

**Comment by k-yoshimi** [comment]
@wistaria
xTAPPはサポート外になっているので、issueを閉じてもいいでしょうか？
