### ISSUE TITLE
python3 の追加

### ISSUE THREAD

**Issue by wistaria** [wistaria/MateriAppsInstaller#58]

**Comment by yomichi** [comment]
sekirei のプリインストールでほしいという意見があったので、確かにそろそろ入れたいところです。
入れるだけなら簡単なんですが、 `env.sh` すると2と3 が両方共 `source` されて、 `python` という名前が衝突するのが少し面倒くさそうだなぁという気はします。

**Comment by yomichi** [comment]
python3 も入ったので、このIssue に特に問題はないと思いますがどうでしょう？
