### ISSUE TITLE
TRIQS、DCore関連のアプリのインストールにつきまして

### ISSUE THREAD

**Issue by mitsuaki1987** [wistaria/MateriAppsInstaller#71]
お世話になっております、物性研の河村です。
DCore開発チームのほうでTRIQS、ALPSCore、DCoreなどをsekireiにインストールした時のノウハウを、DCoreのGitHubのwikiに記述しました。
https://github.com/issp-center-dev/DCore/wiki/Building-DCore-on-sekirei-with-Intel-C-2017-and-gcc5.1
SGIMPTもしくはmpijobの仕様上make testをするとfailedが大量に出ますが、使ってみたところ実用上は問題がないようです。
お役に立ちましたら幸いです。
wannier90(QEに同梱)のインストールなどでご質問がありましたらお尋ねください。

**Comment by k-yoshimi** [comment]
@wistaria 
このissueはcloseしても大丈夫でしょうか？
