### ISSUE TITLE
xTAPPの最新版のダウンロード

### ISSUE THREAD

**Issue by k-yoshimi** [wistaria/MateriAppsInstaller#81]
@wistaria 
xTAPPをsekireiへインストールしようとしたのですが、どのようにスクリプトを変更すればよろしいでしょうか？MateriApps LIVE!の最新版は180420なのですが、現状では150401がインストールされてしまうようです...

ちなみに、xtappの下にあるバージョン番号を
```
XTAPP_VERSION="180420"
XTAPP_PATCH_VERSION="0"
XTAPP_UTIL_VERSION="180420"
XTAPP_UTIL_PATCH_VERSION="0"
XTAPP_PS_VERSION="180420"
XTAPP_PS_PATCH_VERSION="0"
```
に変更したのですが、

```
http://download.sourceforge.net/project/materiappslive/Debian/archive/wheezy/xtapp_180420.orig.tar.gz
download.sourceforge.net をDNSに問いあわせています... 216.105.38.13
download.sourceforge.net|216.105.38.13|:80 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 404 Not Found
2018-08-07 11:51:51 エラー 404: Not Found。
```

というエラーがでてそもそものダウンロードに失敗しました。
素人質問ですみませんが、対応方法についてご教示いただけると助かります。
よろしくお願いします。

**Comment by wistaria** [comment]
@k-yoshimi 
最近、バージョンの付け方を180420から、20180420のように変えました。
あとパッチも修正が必要なようなので、私の方でMateriApps Installerを更新します。

**Comment by k-yoshimi** [comment]
@wistaria 
ありがとうございます。お手数ですがよろしくお願いいたします。

**Comment by k-yoshimi** [comment]
@wistaria 
xTAPPはサポート外になっているので、issueを閉じてもいいでしょうか？

**Comment by k-yoshimi** [comment]
要望があれば対応する。
